"""Fix user table foreign key

Revision ID: 6f9978cd1bc6
Revises: 81a677bf5841
Create Date: 2025-10-29 10:37:42.010905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f9978cd1bc6'
down_revision = '81a677bf5841'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.alter_column('tenant_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('house_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('fk_booking_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_booking_house'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'house', ['house_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_booking_house'), 'house', ['house_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_booking_user'), 'user', ['tenant_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.alter_column('phone',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('house_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('tenant_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
