"""Remove lat and lng from House model

Revision ID: 8a7d6da62cf1
Revises: f0cb4683fcde
Create Date: 2025-10-15 11:58:09.164836

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a7d6da62cf1'
down_revision = 'f0cb4683fcde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_column('lat')
        batch_op.drop_column('lng')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lng', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('lat', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
