"""Add next_rent_payment_due to Booking model

Revision ID: 95be141ddf27
Revises: df438373d902
Create Date: 2025-11-09 23:26:28.922723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95be141ddf27'
down_revision = 'df438373d902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('next_rent_payment_due', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('next_rent_payment_due')

    # ### end Alembic commands ###
