"""Initial migration with Payment and Receipt models

Revision ID: 9eebc129f251
Revises: 
Create Date: 2025-10-13 10:33:29.005990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eebc129f251'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('payment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('appointment_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('appointment_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'service_provider', ['service_provider_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['tenant_id'], ['id'])

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('booking_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('booking_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'house', ['house_id'], ['id'])

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('chat_message_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('chat_message_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['support_agent_id'], ['id'])

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('document_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['tenant_id'], ['id'])

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('event_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['tenant_id'], ['id'])

    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('house_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['owner_id'], ['id'])

    with op.batch_alter_table('maintenance_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('maintenance_request_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['tenant_id'], ['id'])

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('message_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('message_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['sender_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['receiver_id'], ['id'])

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('notification_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['tenant_id'], ['id'])

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('payment_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['tenant_id'], ['id'])

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('review_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('review_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['tenant_id'], ['id'])
        batch_op.create_foreign_key(None, 'service_provider', ['service_provider_id'], ['id'])

    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('service_provider_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('service_request_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('service_request_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'service_provider', ['service_provider_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['tenant_id'], ['id'])

    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('support_ticket_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('support_ticket_ibfk_1'), 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('service_request_ibfk_2'), 'service_provider', ['service_provider_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('service_request_ibfk_1'), 'user', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('service_provider', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('service_provider_ibfk_1'), 'user', ['user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('review_ibfk_1'), 'user', ['tenant_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('review_ibfk_2'), 'service_provider', ['service_provider_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('payment_ibfk_1'), 'user', ['tenant_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('notification_ibfk_1'), 'user', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('message_ibfk_1'), 'user', ['sender_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('message_ibfk_2'), 'user', ['receiver_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('maintenance_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('maintenance_request_ibfk_1'), 'user', ['tenant_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('house_ibfk_1'), 'user', ['owner_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('event_ibfk_1'), 'user', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('document_ibfk_1'), 'user', ['tenant_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('chat_message_ibfk_1'), 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('chat_message_ibfk_2'), 'user', ['support_agent_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('booking_ibfk_2'), 'house', ['house_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('booking_ibfk_1'), 'user', ['tenant_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('appointment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('appointment_ibfk_2'), 'service_provider', ['service_provider_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('appointment_ibfk_1'), 'user', ['tenant_id'], ['id'], ondelete='CASCADE')

    op.drop_table('receipt')
    # ### end Alembic commands ###
