"""Clean up models and fix relationships

Revision ID: b1fe3c4eec63
Revises: 95be141ddf27
Create Date: 2025-11-10 23:31:03.773501

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b1fe3c4eec63'
down_revision = '95be141ddf27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('tenant_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('payment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payment.id'], name=op.f('receipt_ibfk_1')),
    sa.ForeignKeyConstraint(['tenant_id'], ['user.id'], name=op.f('receipt_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
