"""Add house_id to MaintenanceRequest

Revision ID: da6e9c4a4b5c
Revises: ffd02b60c33d
Create Date: 2025-10-23 11:22:13.376914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'da6e9c4a4b5c'
down_revision = 'ffd02b60c33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.alter_column('image_urls',
               existing_type=mysql.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'/static/images/default-house.jpg'"))
        batch_op.alter_column('available',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('availability_date',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text('curdate()'))

    with op.batch_alter_table('maintenance_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('house_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'house', ['house_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'tenant'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'tenant'"))

    with op.batch_alter_table('maintenance_request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('house_id')

    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.alter_column('availability_date',
               existing_type=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('curdate()'))
        batch_op.alter_column('available',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('image_urls',
               existing_type=mysql.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'/static/images/default-house.jpg'"))

    # ### end Alembic commands ###
