"""Add booking_id to Payment model

Revision ID: df438373d902
Revises: 29dbbab659c9
Create Date: 2025-11-09 19:32:43.506976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df438373d902'
down_revision = '29dbbab659c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_for', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('receipt_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('checkout_request_id', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_payment_checkout_request_id'), ['checkout_request_id'], unique=False)
        batch_op.create_unique_constraint(None, ['receipt_id'])
        batch_op.create_foreign_key(None, 'bookings', ['booking_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_payment_checkout_request_id'))
        batch_op.drop_column('checkout_request_id')
        batch_op.drop_column('receipt_id')
        batch_op.drop_column('payment_for')
        batch_op.drop_column('booking_id')

    # ### end Alembic commands ###
