"""Make all House fields not nullable

Revision ID: f0cb4683fcde
Revises: 9eebc129f251
Create Date: 2025-10-15 00:31:41.491220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f0cb4683fcde'
down_revision = '9eebc129f251'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('image_urls',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('lat',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('lng',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('available',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('address_line1',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('address_line2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('state_province',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('postal_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('country',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('rent_amount',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('property_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('bedrooms',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('bathrooms',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('size',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('lease_term',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('availability_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('utilities',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('pets_allowed',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('pet_restrictions',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('parking_availability',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('furnished_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('amenities',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('security_deposit',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('smoking_policy',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('accessibility_features',
               existing_type=mysql.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.alter_column('accessibility_features',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('smoking_policy',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('security_deposit',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('amenities',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('furnished_status',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('parking_availability',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('pet_restrictions',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('pets_allowed',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('utilities',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('availability_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('lease_term',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('size',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('bathrooms',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('bedrooms',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('property_type',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('rent_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('country',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('state_province',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('address_line2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('address_line1',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('owner_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('available',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('lng',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('lat',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('location',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('image_urls',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=mysql.TEXT(),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
