"""Clean up House model

Revision ID: ffd02b60c33d
Revises: 8a7d6da62cf1
Create Date: 2025-10-15 12:23:56.488610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ffd02b60c33d'
down_revision = '8a7d6da62cf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.alter_column('address_line2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('pet_restrictions',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('accessibility_features',
               existing_type=mysql.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('house', schema=None) as batch_op:
        batch_op.alter_column('accessibility_features',
               existing_type=mysql.TEXT(),
               nullable=False)
        batch_op.alter_column('pet_restrictions',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('address_line2',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
